name: Listing Buckets

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  listing_buckets:
    runs-on: ubuntu-latest

    steps:
      - name: Set Up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::357568621764:role/personlWebsite"
          aws-region: eu-north-1

      - name: List S3 Buckets
        run: aws s3 ls
